'use strict';

/* 페이지 정의. tools/build.js 가 이 목록을 읽어 public/ 을 생성한다.
 *
 * slug        출력 경로. '' 이면 index.html, 'privacy' 면 privacy.html
 * body        src/body/ 안의 파일명
 * jsonld      src/jsonld/ 안의 파일명 (없으면 생략)
 * nav         푸터 내비게이션에 노출할지. 노출 순서는 이 배열 순서를 따른다
 * sitemap     sitemap.xml 등록 정보. null 이면 제외
 */

const SITE = 'https://paygyesan.com';

// 애드센스 자동 광고 스크립트. 콘텐츠가 없는 페이지(404)에는 넣지 않는다.
// 내용이 빈약한 페이지에 광고를 다는 것은 애드센스 정책 위반 소지가 있다.
const ADSENSE = '<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1984750615156688" crossorigin="anonymous"></script>';

// 애드센스 ads.txt. 광고 사기 방지용 공개 표준이라 이 내용은 공개되는 것이 정상이다.
// 퍼블리셔 ID 가 바뀌거나 다른 광고 네트워크를 추가하면 여기에 한 줄씩 더한다.
const ADS_TXT = 'google.com, pub-1984750615156688, DIRECT, f08c47fec0942fa0';

const DISCLAIMER_CALC =
  '<strong>면책조항</strong> 이 계산기는 일반적인 법령과 판례를 바탕으로 한 참고용 도구이며, 계산 결과는 법적 효력이 없습니다. ' +
  '실제 금액은 취업규칙, 단체협약, 근로계약서의 구체적인 내용과 사업장 상황에 따라 달라질 수 있습니다. ' +
  '정확한 판단이 필요한 경우 공인노무사 또는 고용노동부 고객상담센터(1350)의 상담을 받으시기 바랍니다. ' +
  '본 사이트는 계산 결과 이용으로 발생한 손해에 대해 책임지지 않습니다.';

const DISCLAIMER_SHORT =
  '<strong>면책조항</strong> 본 사이트의 계산기는 참고용 도구이며 계산 결과는 법적 효력이 없습니다. ' +
  '정확한 판단이 필요한 경우 공인노무사 또는 고용노동부 고객상담센터(1350)의 상담을 받으시기 바랍니다.';

const BADGE = '입력값은 서버로 전송되지 않고 브라우저 안에서만 계산됩니다.';

module.exports = {
  SITE,
  ADS_TXT,
  ADSENSE,
  pages: [
    {
      slug: '',
      body: 'index.html',
      jsonld: 'index.json',
      navLabel: '홈',
      calculator: false,
      nav: true,
      title: '페이계산 | 통상임금·주휴수당·실수령액 계산기',
      h1: '근로자를 위한 임금 계산기',
      lead: '통상시급부터 가산수당, 연봉, 실수령액, 주휴수당까지. <strong>가입 없이 무료로</strong> 계산하세요. 2026년 4대보험 요율과 국세청 간이세액표를 그대로 적용합니다.',
      badge: BADGE,
      description: '한국 근로자를 위한 무료 임금 계산기 모음입니다. 통상임금·통상시급, 연장·야간·휴일근로수당, 세전 연봉과 실수령액, 주휴수당을 가입 없이 계산합니다. 2026년 4대보험 요율과 국세청 근로소득 간이세액표를 반영했습니다.',
      keywords: '임금 계산기, 급여 계산기, 통상임금 계산기, 주휴수당 계산기, 실수령액 계산기, 연봉 계산기, 최저임금, 4대보험 계산',
      robots: 'index, follow, max-snippet:-1, max-image-preview:large',
      ogType: 'website',
      ogTitle: '페이계산 | 통상임금·주휴수당·실수령액 계산기',
      ogDescription: '통상시급부터 가산수당, 연봉, 실수령액, 주휴수당까지 가입 없이 무료로 계산하세요.',
      twTitle: '페이계산 | 임금 계산기 모음',
      twDescription: '통상임금·주휴수당·실수령액을 가입 없이 무료로 계산합니다.',
      disclaimer: DISCLAIMER_CALC,
      sitemap: { priority: '1.0', changefreq: 'monthly' }
    },
    {
      slug: 'yeonbong',
      hubDesc: '세전 연봉만 넣으면 4대보험과 소득세를 뗀 월 실수령액이 나옵니다. 퇴직금 포함 연봉도 구분하고, 연봉별 실수령액표를 함께 봅니다.',
      tags: ['실수령액', '4대보험', '실수령액표'],
      body: 'yeonbong.html',
      jsonld: 'yeonbong.json',
      navLabel: '연봉 실수령액 계산기',
      navShort: '실수령액',
      cardDesc: '세전 연봉만 넣으면 4대보험과 소득세를 뗀 월 실수령액이 나옵니다. 연봉별 실수령액표도 함께 봅니다.',
      calculator: true,
      nav: true,
      title: '연봉 실수령액 계산기 | 2026년 4대보험·세금 반영 - 페이계산',
      h1: '연봉 실수령액 계산기',
      lead: '세전 연봉만 넣으면 4대보험과 소득세를 뗀 <strong>월 실수령액</strong>이 바로 나옵니다. 2026년 요율과 국세청 간이세액표를 적용하고, <strong>퇴직금 포함 연봉</strong>도 구분해 계산합니다.',
      badge: BADGE,
      description: '세전 연봉을 입력하면 4대보험료와 소득세를 뺀 월 실수령액을 계산합니다. 2026년 국민연금 4.75%, 건강보험 3.595% 등 최신 요율과 국세청 근로소득 간이세액표를 적용하며, 퇴직금 포함 연봉 구분과 연봉별 실수령액표를 함께 제공합니다.',
      keywords: '연봉 실수령액, 연봉 실수령액 계산기, 연봉 계산기, 실수령액표, 세후 월급, 월급 실수령액, 4대보험 공제, 퇴직금 포함 연봉, 연봉 3000 실수령액',
      robots: 'index, follow, max-snippet:-1, max-image-preview:large',
      ogType: 'website',
      ogTitle: '연봉 실수령액 계산기 | 2026년 4대보험·세금 반영',
      ogDescription: '세전 연봉만 넣으면 4대보험과 소득세를 뗀 월 실수령액이 즉시 나옵니다.',
      twTitle: '연봉 실수령액 계산기',
      twDescription: '2026년 요율과 국세청 간이세액표를 적용한 연봉 실수령액 계산기.',
      disclaimer: DISCLAIMER_CALC,
      scripts: ['/assets/tax-table.js', '/assets/calc.js', '/assets/yeonbong.js'],
      sitemap: { priority: '0.9', changefreq: 'monthly' }
    },
    {
      slug: 'tongsang',
      hubDesc: '기본급과 수당을 넣으면 통상시급이 나옵니다. 연장·야간·휴일근로수당, 세전 연봉과 영끌 연봉, 4대보험과 소득세를 뗀 월 실수령액까지 한 화면에서 확인합니다.',
      tags: ['통상시급', '가산수당', '연봉', '실수령액'],
      body: 'tongsang.html',
      jsonld: 'tongsang.json',
      navLabel: '통상임금 계산기',
      navShort: '통상임금',
      cardDesc: '기본급과 수당을 넣으면 통상시급, 가산수당, 연봉, 세후 실수령액까지 한 번에 나옵니다.',
      calculator: true,
      nav: true,
      title: '통상임금 계산기 | 통상시급·연봉·실수령액 한 번에 - 페이계산',
      h1: '통상임금 계산기',
      lead: '기본급과 수당을 입력하면 <strong>통상시급</strong>부터 가산수당, <strong>연봉</strong>, <strong>월 실수령액</strong>까지 한 번에 계산합니다. 2024년 12월 대법원 전원합의체 판결과 국세청 간이세액표를 반영했습니다.',
      badge: BADGE,
      description: '기본급·수당·정기상여금을 입력하면 월 통상임금과 통상시급을 바로 계산합니다. 2024년 12월 대법원 전원합의체 판결(고정성 요건 폐기) 반영. 연장·야간·휴일근로수당, 세전 연봉과 영끌 연봉은 물론 국세청 간이세액표를 적용한 월 실수령액까지 한 화면에서 확인하세요. 입력값은 서버에 전송되지 않습니다.',
      keywords: '통상임금, 통상임금 계산기, 통상시급, 연봉 계산기, 실수령액 계산기, 세후 월급, 영끌 연봉, 4대보험 계산, 간이세액표, 연장근로수당, 야간근로수당, 휴일근로수당, 209시간',
      robots: 'index, follow, max-snippet:-1, max-image-preview:large',
      ogType: 'website',
      ogTitle: '통상임금 계산기 | 통상시급·연봉·실수령액 한 번에',
      ogDescription: '기본급·수당·정기상여금을 입력하면 통상시급, 가산수당, 영끌 연봉, 월 실수령액까지 즉시 계산합니다.',
      twTitle: '통상임금 계산기 | 통상시급·연봉·실수령액',
      twDescription: '2024년 대법원 판결과 국세청 간이세액표를 반영한 통상임금·연봉·실수령액 계산기.',
      disclaimer: DISCLAIMER_CALC,
      scripts: ['/assets/tax-table.js', '/assets/calc.js', '/assets/tongsang.js'],
      sitemap: { priority: '0.9', changefreq: 'monthly' }
    },
    {
      slug: 'boheom',
      body: 'boheom.html',
      jsonld: 'boheom.json',
      navLabel: '4대보험 계산기',
      navShort: '4대보험',
      hubDesc: '월 급여를 넣으면 국민연금·건강보험·장기요양·고용보험료가 나옵니다. 근로자 부담뿐 아니라 사업주 부담과 회사가 실제로 쓰는 인건비까지 함께 보여줍니다.',
      tags: ['4대보험', '사업주 부담', '인건비'],
      cardDesc: '월 급여를 넣으면 근로자 부담과 사업주 부담을 나눠 계산합니다. 회사가 실제로 쓰는 인건비까지 나옵니다.',
      calculator: true,
      nav: true,
      title: '4대보험 계산기 | 근로자·사업주 부담 2026년 요율 - 페이계산',
      h1: '4대보험 계산기',
      lead: '월 급여만 넣으면 국민연금·건강보험·장기요양·고용보험료가 바로 나옵니다. <strong>근로자 부담</strong>과 <strong>사업주 부담</strong>을 나눠 보여주고, 회사가 실제로 쓰는 인건비까지 계산합니다.',
      badge: BADGE,
      description: '월 급여를 입력하면 국민연금·건강보험·장기요양·고용보험료를 근로자 부담분과 사업주 부담분으로 나눠 계산합니다. 2026년 요율, 국민연금 기준소득월액 상·하한, 기업 규모별 고용안정·직업능력개발사업 요율을 반영했습니다.',
      keywords: '4대보험 계산기, 4대보험 요율, 국민연금 계산, 건강보험료 계산, 장기요양보험료, 고용보험료, 사업주 부담금, 인건비 계산',
      robots: 'index, follow, max-snippet:-1, max-image-preview:large',
      ogType: 'website',
      ogTitle: '4대보험 계산기 | 근로자·사업주 부담 2026년 요율',
      ogDescription: '월 급여만 넣으면 근로자 부담과 사업주 부담을 나눠 계산합니다.',
      twTitle: '4대보험 계산기 | 근로자·사업주 부담',
      twDescription: '2026년 요율로 근로자·사업주 부담과 회사 인건비를 계산합니다.',
      disclaimer: DISCLAIMER_CALC,
      scripts: ['/assets/calc.js', '/assets/boheom.js'],
      sitemap: { priority: '0.9', changefreq: 'monthly' }
    },
    {
      slug: 'yeongeum',
      hubDesc: '가입 이력 없이도 국민연금 예상 수령액을 계산합니다. 2026년 A값과 가입 연도별 비례상수, 조기수급·연기연금까지 반영했습니다.',
      tags: ['국민연금', '예상 수령액', '조기수급'],
      body: 'yeongeum.html',
      jsonld: 'yeongeum.json',
      navLabel: '국민연금 예상 수령액 계산기',
      navShort: '국민연금',
      cardDesc: '출생연도와 가입기간, 현재 소득만 넣으면 매달 받을 연금액이 나옵니다. 언제부터 받느냐에 따라 얼마나 달라지는지도 함께 비교합니다.',
      calculator: true,
      nav: true,
      title: '국민연금 예상 수령액 계산기 | 2026년 개혁 반영 - 페이계산',
      h1: '국민연금 예상 수령액 계산기',
      lead: '출생연도와 가입기간, 현재 소득만 넣으면 <strong>매달 받을 연금액</strong>이 바로 나옵니다. 2026년 A값 3,193,511원과 가입 연도별 비례상수, 조기수급·연기연금 지급률을 반영했습니다.',
      badge: BADGE,
      description: '국민연금 노령연금 예상 수령액을 계산합니다. 가입 이력 없이 출생연도·가입기간·현재 소득만으로 추정하며, 2026년 A값 3,193,511원, 가입 연도별 비례상수(1988~1998년 2.4 · 2026년 이후 1.29), 20년 미만 지급률, 조기수급 감액과 연기연금 가산을 모두 반영했습니다.',
      keywords: '국민연금 예상 수령액, 국민연금 계산기, 노령연금, 국민연금 수령액 조회, 조기노령연금, 연기연금, 소득대체율 43%, 국민연금 개혁, A값, 비례상수',
      robots: 'index, follow, max-snippet:-1, max-image-preview:large',
      ogType: 'website',
      ogTitle: '국민연금 예상 수령액 계산기 | 2026년 개혁 반영',
      ogDescription: '출생연도와 가입기간, 현재 소득으로 매달 받을 국민연금을 계산합니다. 조기수급·연기연금 비교까지.',
      twTitle: '국민연금 예상 수령액 계산기',
      twDescription: '2026년 A값과 가입 연도별 비례상수를 반영한 국민연금 예상 수령액 계산기.',
      disclaimer: DISCLAIMER_CALC,
      scripts: ['/assets/calc.js', '/assets/yeongeum.js'],
      sitemap: { priority: '0.9', changefreq: 'monthly' }
    },
    {
      slug: 'juhyu',
      hubDesc: '시급과 근무시간만 넣으면 주휴수당과 주급, 월 환산액이 나옵니다. 주 15시간 조건과 최저임금 미달 여부도 함께 알려줍니다.',
      tags: ['주휴수당', '주급', '최저임금'],
      body: 'juhyu.html',
      jsonld: 'juhyu.json',
      navLabel: '주휴수당 계산기',
      navShort: '주휴수당',
      cardDesc: '시급과 근무시간을 넣으면 주휴수당과 주급, 월 환산액을 계산합니다. 최저임금 미달도 확인합니다.',
      calculator: true,
      nav: true,
      title: '주휴수당 계산기 | 알바·단시간 근로자 주휴수당 - 페이계산',
      h1: '주휴수당 계산기',
      lead: '시급과 근무시간만 넣으면 <strong>주휴수당</strong>과 주급, 월급 환산액을 바로 계산합니다. 주 15시간 미만 여부와 최저임금 미달까지 함께 확인합니다.',
      badge: BADGE,
      description: '시급과 주 근무시간을 입력하면 주휴수당을 바로 계산합니다. 주 15시간 이상 여부, 단시간 근로자 비례 계산, 최저임금 미달 여부, 주급·월급 환산까지 한 번에 확인하세요. 입력값은 서버에 전송되지 않습니다.',
      keywords: '주휴수당, 주휴수당 계산기, 주휴수당 조건, 알바 주휴수당, 단시간 근로자 주휴수당, 주 15시간, 최저임금, 주급 계산',
      robots: 'index, follow, max-snippet:-1, max-image-preview:large',
      ogType: 'website',
      ogTitle: '주휴수당 계산기 | 알바·단시간 근로자',
      ogDescription: '시급과 근무시간만 넣으면 주휴수당과 주급·월급 환산액을 즉시 계산합니다.',
      twTitle: '주휴수당 계산기 | 알바·단시간 근로자',
      twDescription: '주 15시간 조건과 최저임금 미달 여부까지 확인하는 주휴수당 계산기.',
      disclaimer: DISCLAIMER_CALC,
      scripts: ['/assets/calc.js', '/assets/juhyu.js'],
      sitemap: { priority: '0.9', changefreq: 'monthly' }
    },
    {
      slug: 'toejik',
      hubDesc: '입사일과 퇴직 전 3개월 임금을 넣으면 1일 평균임금과 예상 퇴직금이 나옵니다. 상여금·연차수당 산입과 통상임금 비교까지 반영합니다.',
      tags: ['퇴직금', '평균임금', '재직일수'],
      body: 'toejik.html',
      jsonld: 'toejik.json',
      navLabel: '퇴직금 계산기',
      navShort: '퇴직금',
      cardDesc: '입사일과 퇴직 전 3개월 임금을 넣으면 평균임금과 예상 퇴직금이 나옵니다. 통상임금과 비교해 유리한 쪽을 적용합니다.',
      calculator: true,
      nav: true,
      title: '퇴직금 계산기 | 평균임금 기준 예상 퇴직금 - 페이계산',
      h1: '퇴직금 계산기',
      lead: '입사일과 마지막 근무일, 퇴직 전 3개월 임금을 넣으면 <strong>평균임금</strong>과 <strong>예상 퇴직금</strong>이 바로 나옵니다. 상여금·연차수당의 3/12 산입과 통상임금 비교까지 반영합니다.',
      badge: BADGE,
      description: '입사일과 마지막 근무일, 퇴직 전 3개월 임금을 입력하면 1일 평균임금과 예상 퇴직금을 계산합니다. 상여금·연차수당의 3/12 산입, 평균임금과 통상임금 비교, 계속근로기간 1년 요건까지 반영했습니다. 입력값은 서버에 전송되지 않습니다.',
      keywords: '퇴직금 계산기, 퇴직금 계산법, 평균임금 계산, 1일 평균임금, 퇴직금 지급기준, 퇴직연금 DB DC, 퇴직소득세, 계속근로기간',
      robots: 'index, follow, max-snippet:-1, max-image-preview:large',
      ogType: 'website',
      ogTitle: '퇴직금 계산기 | 평균임금 기준 예상 퇴직금',
      ogDescription: '입사일과 3개월 임금만 넣으면 평균임금과 예상 퇴직금을 즉시 계산합니다.',
      twTitle: '퇴직금 계산기 | 평균임금 기준',
      twDescription: '상여금·연차수당 산입과 통상임금 비교까지 반영한 퇴직금 계산기.',
      disclaimer: DISCLAIMER_CALC,
      scripts: ['/assets/calc.js', '/assets/toejik.js'],
      sitemap: { priority: '0.9', changefreq: 'monthly' }
    },
    {
      slug: 'yeoncha',
      hubDesc: '입사일만 넣으면 연차가 며칠 발생하는지 나옵니다. 남은 연차를 돈으로 환산한 미사용수당도 함께 계산합니다.',
      tags: ['연차일수', '미사용수당', '가산휴가'],
      body: 'yeoncha.html',
      jsonld: 'yeoncha.json',
      navLabel: '연차수당 계산기',
      navShort: '연차수당',
      cardDesc: '입사일만 넣으면 발생 연차일수가 나오고, 통상임금으로 미사용 연차수당까지 계산합니다.',
      calculator: true,
      nav: true,
      title: '연차수당 계산기 | 연차 발생일수와 미사용수당 - 페이계산',
      h1: '연차수당 계산기',
      lead: '입사일만 넣으면 <strong>연차 발생일수</strong>가 바로 나옵니다. 월 통상임금을 더하면 <strong>미사용 연차수당</strong>까지 계산합니다. 가산휴가와 25일 한도를 반영했습니다.',
      badge: BADGE,
      description: '입사일을 입력하면 근로기준법 제60조에 따른 연차 발생일수를 계산합니다. 1년 미만 월 1일, 1년 이상 15일, 3년차부터 2년마다 가산되는 규칙과 25일 한도를 반영했으며, 월 통상임금으로 미사용 연차수당까지 산출합니다.',
      keywords: '연차수당, 연차수당 계산기, 연차 계산기, 연차 발생일수, 연차 미사용수당, 근로기준법 제60조, 가산휴가, 연차사용촉진',
      robots: 'index, follow, max-snippet:-1, max-image-preview:large',
      ogType: 'website',
      ogTitle: '연차수당 계산기 | 연차 발생일수와 미사용수당',
      ogDescription: '입사일만 넣으면 연차 발생일수가 나오고, 통상임금으로 미사용수당까지 계산합니다.',
      twTitle: '연차수당 계산기 | 발생일수와 미사용수당',
      twDescription: '근로기준법 제60조 가산휴가와 25일 한도를 반영한 연차수당 계산기.',
      disclaimer: DISCLAIMER_CALC,
      scripts: ['/assets/calc.js', '/assets/yeoncha.js'],
      sitemap: { priority: '0.9', changefreq: 'monthly' }
    },
    {
      slug: 'silup',
      hubDesc: '퇴사 후 실업급여를 얼마나, 며칠 동안 받을 수 있는지 계산합니다. 2026년 상한·하한액과 소정급여일수를 반영했습니다.',
      tags: ['구직급여', '소정급여일수', '피보험기간'],
      body: 'silup.html',
      jsonld: 'silup.json',
      navLabel: '실업급여 계산기',
      navShort: '실업급여',
      cardDesc: '이직 전 3개월 임금과 근무 기간을 넣으면 1일 구직급여와 소정급여일수, 총 수급액이 나옵니다.',
      calculator: true,
      nav: true,
      title: '실업급여 계산기 | 구직급여 일액과 소정급여일수 - 페이계산',
      h1: '실업급여 계산기',
      lead: '이직 전 3개월 임금과 근무 기간을 넣으면 <strong>1일 구직급여</strong>와 <strong>소정급여일수</strong>, 총 예상 수급액이 바로 나옵니다. 2026년 상한액 68,100원·하한액 66,048원을 반영했습니다.',
      badge: BADGE,
      description: '입사일과 마지막 근무일, 이직 전 3개월 임금을 입력하면 구직급여 1일 지급액과 소정급여일수, 총 예상 수급액을 계산합니다. 2026년 상한액 68,100원과 하한액 66,048원, 고용보험법 별표1 소정급여일수를 반영했습니다.',
      keywords: '실업급여, 실업급여 계산기, 구직급여, 실업급여 상한액, 실업급여 하한액, 소정급여일수, 피보험기간, 실업급여 조건, 자발적 퇴사 실업급여',
      robots: 'index, follow, max-snippet:-1, max-image-preview:large',
      ogType: 'website',
      ogTitle: '실업급여 계산기 | 구직급여 일액과 소정급여일수',
      ogDescription: '이직 전 3개월 임금과 근무 기간으로 1일 구직급여와 총 수급액을 즉시 계산합니다.',
      twTitle: '실업급여 계산기 | 구직급여 계산',
      twDescription: '2026년 상한액·하한액과 고용보험법 별표1을 반영한 실업급여 계산기.',
      disclaimer: DISCLAIMER_CALC,
      scripts: ['/assets/calc.js', '/assets/silup.js'],
      sitemap: { priority: '0.9', changefreq: 'monthly' }
    },
    {
      slug: 'yuka',
      hubDesc: '육아휴직 급여를 월별로 얼마 받는지 계산합니다. 2025년 개편된 상한액과 6+6 부모육아휴직제를 반영했습니다.',
      tags: ['육아휴직', '월별 지급액', '6+6'],
      body: 'yuka.html',
      jsonld: 'yuka.json',
      navLabel: '육아휴직 급여 계산기',
      navShort: '육아휴직',
      cardDesc: '통상임금과 사용 기간을 넣으면 월별 육아휴직 급여와 총 수령액이 나옵니다. 6+6 부모육아휴직제도 반영합니다.',
      calculator: true,
      nav: true,
      title: '육아휴직 급여 계산기 | 월별 지급액과 총 수령액 - 페이계산',
      h1: '육아휴직 급여 계산기',
      lead: '월 통상임금과 사용 기간만 넣으면 <strong>월별 지급액</strong>과 <strong>총 수령액</strong>이 바로 나옵니다. 2025년 개편된 구간별 상한액과 6+6 부모육아휴직제를 반영했습니다.',
      badge: BADGE,
      description: '월 통상임금과 사용 기간을 입력하면 육아휴직 급여를 월별로 계산합니다. 1~3개월 250만 원, 4~6개월 200만 원, 7개월 이후 160만 원의 구간별 상한액, 하한액 70만 원, 사후지급금 폐지, 6+6 부모육아휴직제를 모두 반영했습니다.',
      keywords: '육아휴직 급여, 육아휴직 급여 계산기, 육아휴직 상한액, 6+6 부모육아휴직제, 사후지급금 폐지, 육아휴직 1년 6개월, 육아휴직 조건',
      robots: 'index, follow, max-snippet:-1, max-image-preview:large',
      ogType: 'website',
      ogTitle: '육아휴직 급여 계산기 | 월별 지급액과 총 수령액',
      ogDescription: '통상임금과 사용 기간으로 육아휴직 급여를 월별로 계산합니다. 6+6 부모육아휴직제 반영.',
      twTitle: '육아휴직 급여 계산기',
      twDescription: '2025년 개편 상한액과 6+6 부모육아휴직제를 반영한 육아휴직 급여 계산기.',
      disclaimer: DISCLAIMER_CALC,
      scripts: ['/assets/calc.js', '/assets/yuka.js'],
      sitemap: { priority: '0.9', changefreq: 'monthly' }
    },
    {
      slug: 'privacy',
      body: 'privacy.html',
      navLabel: '개인정보처리방침',
      nav: true,
      title: '개인정보처리방침 | 페이계산 통상임금 계산기',
      h1: '개인정보처리방침',
      lead: '시행일 2026년 1월 1일',
      description: '페이계산(paygyesan.com)의 개인정보처리방침입니다. 이용자가 입력한 급여 정보는 서버로 전송되거나 저장되지 않으며 브라우저 안에서만 처리됩니다.',
      robots: 'index, follow',
      ogType: 'article',
      ogTitle: '개인정보처리방침 | 페이계산',
      ogDescription: '입력한 급여 정보는 서버로 전송되거나 저장되지 않습니다.',
      twTitle: '개인정보처리방침 | 페이계산',
      twDescription: '입력한 급여 정보는 서버로 전송되거나 저장되지 않습니다.',
      disclaimer: DISCLAIMER_SHORT,
      sitemap: { priority: '0.3', changefreq: 'yearly' }
    },
    {
      slug: '404',
      body: '404.html',
      nav: false,
      ads: false,
      title: '페이지를 찾을 수 없습니다 | 페이계산',
      h1: '페이지를 찾을 수 없습니다',
      lead: '주소가 바뀌었거나 삭제된 페이지입니다.',
      description: '요청하신 페이지가 없습니다. 페이계산 계산기로 돌아가세요.',
      robots: 'noindex, follow',
      ogType: 'website',
      ogTitle: '페이지를 찾을 수 없습니다 | 페이계산',
      ogDescription: '요청하신 페이지가 없습니다.',
      twTitle: '페이지를 찾을 수 없습니다',
      twDescription: '요청하신 페이지가 없습니다.',
      sitemap: null
    }
  ]
};
